engines/admin/config/routes.rb
Admin::Engine.routes.draw do
  devise_for :administrators, class_name: "Admin::Administrator"
  resources :administrators
end

engines/admin/app/models/admin/administrator.rb
module Admin
  class Administrator < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
  end
end

engines/admin/app/models/admin/application_record.rb
module Admin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/admin/app/controllers/admin/administrators_controller.rb
require_dependency "admin/application_controller"

module Admin
  class AdministratorsController < ApplicationController
    before_action :set_administrator, only: [:show, :edit, :update, :destroy]

    # GET /administrators
    def index
      @administrators = Administrator.all
    end

    # GET /administrators/1
    def show
    end

    # GET /administrators/new
    def new
      @administrator = Administrator.new
    end

    # GET /administrators/1/edit
    def edit
    end

    # POST /administrators
    def create
      @administrator = Administrator.new(administrator_params)

      if @administrator.save
        redirect_to @administrator, notice: 'Administrator was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /administrators/1
    def update
      if @administrator.update(administrator_params)
        redirect_to @administrator, notice: 'Administrator was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /administrators/1
    def destroy
      @administrator.destroy
      redirect_to administrators_url, notice: 'Administrator was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_administrator
        @administrator = Administrator.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def administrator_params
        params.require(:administrator).permit(:name)
      end
  end
end

engines/admin/app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

engines/admin/app/helpers/admin/administrators_helper.rb
module Admin
  module AdministratorsHelper
  end
end

engines/admin/app/helpers/admin/application_helper.rb
module Admin
  module ApplicationHelper
  end
end

engines/admin/app/views/admin/administrators/_form.html.erb
<%= form_with(model: administrator, local: true) do |form| %>
  <% if administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% administrator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :administrator_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

engines/admin/app/views/admin/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form', administrator: @administrator %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

engines/admin/app/views/admin/administrators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Administrators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.name %></td>
        <td><%= link_to 'Show', administrator %></td>
        <td><%= link_to 'Edit', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_administrator_path %>

engines/admin/app/views/admin/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form', administrator: @administrator %>

<%= link_to 'Back', administrators_path %>

engines/admin/app/views/admin/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @administrator.name %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>

engines/admin/app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>
  <%= stylesheet_link_tag    "admin/application", media: "all" %>
  <%= javascript_include_tag "admin/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>